### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by nothendev** [Implodent/oxcraft#7]
This issue covers the proxy crate's road to MVP.

## Tasks
- [x] Initialize the proxy crate
- [ ] Add configuration for server routes
- [ ] Implement the login process
- [ ] Implement full packet routing
- [ ] Implement forced hosts
